name: Build Voice Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install 32-bit toolchain
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y g++-multilib gcc-multilib cmake make

      - name: Build plugin (.so 32-bit)
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ls -l

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: voice_samp_linux
          path: build/*.so

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build plugin (.dll 32-bit)
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
          dir build/Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: voice_samp_windows
          path: build/Release/*.dll
