name: Build voice_samp plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
        include:
          - os: ubuntu-20.04
            ext: so
          - os: windows-latest
            ext: dll

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up MSVC (Windows only)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install build tools (Linux only)
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build plugin
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-20.04" ]; then
          g++ -m32 -std=c++17 -O2 -fPIC -shared voice_samp.cpp -o voice_samp.${{ matrix.ext }}
        else
          cl /LD /EHsc voice_samp.cpp ws2_32.lib /Fe:voice_samp.${{ matrix.ext }}
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: voice_samp-${{ matrix.os }}
        path: voice_samp.${{ matrix.ext }}
